name: Build and Push Frontend Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build Image
              run: |
                  docker build \
                    -t ghcr.io/${{ github.repository_owner }}/prod-lab-frontend:${{ github.sha }} \
                    -t ghcr.io/${{ github.repository_owner }}/prod-lab-frontend:main .

            - name: Push Image
              run: |
                  docker push ghcr.io/${{ github.repository_owner }}/prod-lab-frontend:${{ github.sha }}
                  docker push ghcr.io/${{ github.repository_owner }}/prod-lab-frontend:main
